<?php //006fb
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Auftragsmanager @version 5.1.1.3 PHP73 (03.05.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPpiu8gmb1fU3C8otZqRhGFbRgtjjsN9+ER6uBqoo+l77bmatJClRnGULfe5o62Z0CnUqmtpG
ANEajDM/tlF4HGMjLDxqm4RNu8E1jtNth86kBHKmgJujmab8f8sToWkl7wy42k2WTdR2kLUFs7Dx
2yszCoWrLZNxfzPF0pTMViIf+7u6WN8YQVBtb6oCXwg5AQUXzd6ystuhjJTQTVZYEl5k538NbCtf
JSyPPcA9Qo5zr7PhpiDNOCFBM7Umn4SdZgW0eZ7XNUScGOkXExPG7uLP4dvfglgOt32qvXNx/f9N
/RGLoC4ffhx4GBT+qCpyCskypszj+CSnS27g5J7zEWL6y+TVoTHjiM7B22p7zwmaDOeJvPRVMZjN
Ep99sOHnknxrn/cgd4IH1/6YOyoNO6eO7QibhE91A2csT566ISOQHdnIbreMNr6+Z3q8Hxctplru
DZIqeswafClmtlkTb7Kp6yQgOeeowYWp7G9F1PMqvdYYZFqcUoeu98XL1b5B6uSpyphpTLzM8maC
ZxQwaRUBFx6LLLl6Fs8VM0/rHzhFwesnUt4F4sKpqEtPlNbYG3K=