<?php //006fb
// <?php /** This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Auftragsmanager @version 5.1.3.0 PHP73 (07.09.2023) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2023, D3 Data Development @see https://www.d3data.de */ ?>
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cP+BCRAm5AbM4q7ZvZqq2mszoW7SiTlI9URkupvaiLyjppQ8d2xFSInBgxU9GRgU05SrkrvXM
l2GM28ouCVpXiGQyDZvVAYzgRn5KIVgj4i21XIN1jtDVBITN9xI3CwK919RtZcx1cpAmFUgeoHzy
30vWxiXyM9vMcuDQMmqFqt40Qa+Ap2858+Nx/O85bXkvRYL5BWe4tk0h6T9YccTm3uXcGky1BHTd
skc/vLSh7x7zeV9jxK0CJdmu3pYKtPbcOQCWTRiauQ+P1o9xDJaQpLd04wvW/ZlShof/le1I4Nm4
XwWgtuLrC6Gbcya66L702DT0Ewls275tZbgvYqFfUlB3f7sCVzwNXkez3BUdq38MKwfl8gSjoSmc
8WBypdmc00VJtLjF4uVu5Doz3WZBHBYUASDCRQ1uVEYVrIs5jPG1ZGUJreMsQwQMSwSt2HmUFrVz
/JduUHHVTsznP12Vxx9vwQfCbkt/ek5SC1F2Vhb63ZL8rPlBjBYsAdpRFbpT1A06uP2E0FJnBkQk
WNXpWslj0HRcRaCHCgLFCqXSCfLEn2CjWB8pBEGlbhTdBxaKCU3xDQm4YbK9H1pExT4+qa/x5Fsh
CMmxqG==