<?php //006ef
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Auftragsmanager @version 4.1.2.2 PHP71 (07.05.2021) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2021, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPoNFDHr35uvI6dkWFZO3QWZ6Xx1wmDP5zP+uLhmvvO9u6WWpbs748sVVi5js3cr/QosMrx69
ZktGAETdTbvLdZNHLcXUN4vvQTIVynMMsf24EYDqLiTWLk/pzOy3AyAaEtPDIhI6DDIGkqjPMRVa
O+V1sWTn/r60a7aV7GK7YOjxPprTClvx9SMAqjc2yO4aak0uOvxNhtliAq9sbACEi66K3fnK7g91
r/JQzXTQQvzMSMlsD3GpPRnEY4dmsliMyTacjUqlnh1jZ027mkV4KB+Sc9febsduJJ6o2n4KnbLi
vyC2cITdb31Oov4BsAMJFyW0EbpPHcmBWDpnAmoDyCfyHYLgRiXzr360TOBEsftpVX2CbocJbPlk
YKoI2huMZCEpsEpieP5vq1yUcMm3a3arkeVcrxJuv1+DsfO3ZivtPzVzRnxY0Cp5KsOkiar1gcQr
oOycaTUqCfx8o40dSSxfSlRz5lCmf0DYE5xhvOscMiAH4EaepKcKt9DuA88KGaDYTwNp1K+sbfGU
cH6HcFrWxgeL1IGuG0Tkx/QL59MxUZhQQ8+ZlZKOyiWJAOSoXhBSKjggATZLnvoVyY7EDO54RKxc
j7XppEG=